import Head from 'next/head'

import { useContext } from 'react'
import { DarkModeContext } from '@/context/darkMode.context'

const Home = () => {
  const { darkMode } = useContext(DarkModeContext)

  return (
    <>
      <Head>
        <title>Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div></div>
      </main>
    </>
  )
}

export default Home
